FROM oven/bun:1.3.11

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY src ./src
COPY tsconfig.json ./

ENV PORT=3000
EXPOSE 3000

CMD ["bun", "run", "src/index.ts"]
